### ISSUE TITLE
safari extension not working

### ISSUE THREAD

**Issue by chantellecv** [Zaquum/LeetHub-in-Safari#1]
The leethub v2 folder which should contain the safari extension has no manifest.json file which makes it impossible to convert to the safari extension using xcrun. The leethub-2.0 folder contains the manifest.json file but works only for chrome and not safari. When that folder is converted for safari and the extension is run, users are not able to authenticate their github accounts since the authenticate button does not work.

**Comment by sirgypsyg** [comment]
Also doesn't work here as I installed through Xcode 'LeetHub v2' it added the extension to safari but clicking authenticate just doesn't do anything. 
<img width="409" alt="Screenshot 2024-02-20 at 19 14 52" src="https://github.com/Zaquum/LeetHub-in-Safari/assets/107400417/21133310-b8d5-49f6-8da0-d3eae85f7407">

**Comment by Zaquum** [comment]
I'm sorry to get back too late, @chantellecv, @sirgypsyg 

I think I've confused you. The leethub v2 folder is converted folder for extension. I deleted the folder to prevent the confusion. You just convert the folder 'LeetHub-2.0'. Before converting the folder, you just check following 'Show Develop menu in menu bar” box > Allow Unsigned Extensions'.
After activating the safari extension, you authenticate your github and connect to your repository. If you connect to existing repository, it can be not work. In that case, You may choose to create a new repository.
I checked that the latest version does work properly with my safari.
<img width="338" alt="image" src="https://github.com/Zaquum/LeetHub-in-Safari/assets/111241979/b7be50cc-da4b-41b8-8cb5-645ec01935e5">
If you have any difficulties along the way, please tell me again. Posting a picture will help you more
